trigger:
  branches:
    include:
      - main

pool:
  name: COMP367-Lab

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
      npm run build
    displayName: 'Build React App'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'build'
      ArtifactName: 'reactapp'
    displayName: 'Publish Build Artifacts'
